### ISSUE TITLE
Custom komi on demo boards breaks "Game Information" panel

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#2531]
From the forums:
https://forums.online-go.com/t/request-custom-komi-for-demo-board/39065/20

> I’m getting an error when trying to open the information box when I’ve specified 0.5 komi
> 
> https://online-go.com/demo/view/1212487)
>
> TypeError: i.komi.toFixed is not a function.

Caused by #2501.

**Comment by dexonsmith** [comment]
Confirmed that normal games don't have this bug (even with custom komi).

**Comment by dexonsmith** [comment]
This is what's triggering the error:
```
                        <dt>{_("Komi")}</dt>
                        <dd>{config.komi!.toFixed(1)}</dd>
```
My guess is that for some reason `config.komi` is a string or undefined instead of a float in this context. I created a demo game where this triggers and played it out far enough that I could get something predictable out of "Estimate Score" and confirmed that that function works correctly. It seems to only affect the web-client.

**Comment by dexonsmith** [comment]
Yup, console confirms `undefined`:
```
TypeError: i.komi.toFixed is not a function. (In 'i.komi.toFixed(1)', 'i.komi.toFixed' is undefined)
```

**Comment by dexonsmith** [comment]
Seems to be a string, since it displays as expected if I just print `config.komi`.

**Comment by dexonsmith** [comment]
Confirmed that normal games with custom komi were NOT broken by this.
